name: Tag Release

on:
  push:
    tags:
      - "v*.*.*"          # Stable
      - "v*.*.*-dev.*"    # Dev
      - "v*.*.*-alpha.*"  # Alpha
      - "v*.*.*-beta.*"   # Beta
      - "v*.*.*-rc.*"     # RC

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: true
          format: true
      - name: Generate SDK
        run: buf generate
      - name: Publish Go SDK
        run: |
          git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com/forgoes/proto-go
          cd proto-go
          shopt -s extglob
          rm -rf !(go.mod|README.md|LICENSE|.gitignore|.git)
          cp -r ../gen/go/* .
  
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Update SDK for $GITHUB_REF_NAME" || echo "No changes to commit"

          git push origin main
          
          git tag $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME